POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "usuarioum",
  "password": "Usuarioum@22112022"
}

POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "usuariodois",
  "password": "Usuariodois@22112022"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "usuarioum",
  "password": "Usuarioum@22112022"
}

###
GET http://localhost:3000/users/view-balance
Authorization: Bearer


###
POST http://localhost:3000/transactions/money-transfer
Authorization: Bearer 
Content-Type: application/json

{
  "usernameCashIn": "usuariodois",
  "value": 14.68
}

###
GET http://localhost:3000/transactions/find-transactions?createdAt=2022-11-22&cashIn=yes&cashOut=no
Authorization: Bearer 
