POST http://localhost:3000/users/create
Content-Type: application/json

{
  "username": "isaiasiotti",
  "password": "Kero@10062022"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
  "username": "isaiasiotti",
  "password": "Kero@10062022"
}

###
GET http://localhost:3000/users/view-balance
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTFmNWZlMi02ZjQ4LTRjMTYtOGIxZi1iODMyYmE5MzFhZjciLCJ1c2VybmFtZSI6ImlzYWlhc2lvdHRpIiwiYWNjb3VudElkIjoiMGQ3NjZhMDgtZjkxZS00MzgxLTk0MTctM2JhZTQ3YjI2ZGNhIiwiaWF0IjoxNjY5MTUzNDE0LCJleHAiOjE2NjkyMzk4MTR9.oTCHR_34A6pNBFiD3xVxOj3cZu1FkrSzQw3fuDwWshY


###
POST http://localhost:3000/transactions/money-transfer
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTFmNWZlMi02ZjQ4LTRjMTYtOGIxZi1iODMyYmE5MzFhZjciLCJ1c2VybmFtZSI6ImlzYWlhc2lvdHRpIiwiYWNjb3VudElkIjoiMGQ3NjZhMDgtZjkxZS00MzgxLTk0MTctM2JhZTQ3YjI2ZGNhIiwiaWF0IjoxNjY5MTUzNDE0LCJleHAiOjE2NjkyMzk4MTR9.oTCHR_34A6pNBFiD3xVxOj3cZu1FkrSzQw3fuDwWshY
Content-Type: application/json

{
  "usernameCashIn": "kerolainebrandao",
  "value": 14.68
}

###
GET http://localhost:3000/transactions/find-transactions?createdAt=2022-11-22&cashIn=yes&cashOut=no
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1NTFmNWZlMi02ZjQ4LTRjMTYtOGIxZi1iODMyYmE5MzFhZjciLCJ1c2VybmFtZSI6ImlzYWlhc2lvdHRpIiwiYWNjb3VudElkIjoiMGQ3NjZhMDgtZjkxZS00MzgxLTk0MTctM2JhZTQ3YjI2ZGNhIiwiaWF0IjoxNjY5MTUzNDE0LCJleHAiOjE2NjkyMzk4MTR9.oTCHR_34A6pNBFiD3xVxOj3cZu1FkrSzQw3fuDwWshY
